### PR TITLE
Fix Task cancellation leaks

### LINKED ISSUE #866: Memory Leak in LiveKitWebRTC when streaming via BufferCapturer
Hi @pblazej and @hiroshihorie ,
this is a follow-up to my previous report:  
[Previous issue: Memory Leaking - High memory after Room.disconnect #827](https://github.com/livekit/client-sdk-swift/issues/827)

I can now provide a minimal, runnable LiveKit + ARKit reproduction project that isolates the leak.  
This project contains only the essential components from the LiveKit example plus a minimal custom AR → BufferCapturer bridge.  
This issue focuses **exclusively on internal leaks**.

---

## Summary

The minimal project supports two Room lifecycle modes:

- **Global shared Room instance** (matching the original LiveKit Example)  
  → Reproduces **one leak(LiveKitWebRTC)**

- **Per-connection mode** (fresh `Room()` for each join)  
  → After a leave + rejoin, Instruments reports **more than 24 leaks**

In the per-connection mode, the previous `Room` instance becomes unreachable from the app side (replaced by a new placeholder `Room`), but internal LiveKit objects remain alive and are reported as leaks.

---

## Minimal Reproduction Project

@pblazej and @hiroshihorie, I invited you to the private GitHub project.

The project is a very small SwiftUI app based on these components from the official LiveKit examples:

- `RoomSwitchView`  
- `RoomContextView`  
- `ParticipantView`  
- `ConnectView`  
- `LKButton`, `LKTextField`  
- `SecureStore`  
- `Participant+Helper`  
- `ExampleRoomMessage`  
- `ConnectionHistory`  
- `Bundle` helper  

Added on top:

- A minimal ARKit → BufferCapturer bridge (`ARVideoCapturer`) publishing AR frames as a `LocalVideoTrack`.

---

## How to Run the Minimal Setup

1. **Clone** the provided sample project.  
2. **Configure your LiveKit server URL and token** in `RoomContext` (file: `RoomContext.swift`):

   ```swift
   url = "wss://<your-livekit-host>.livekit.cloud"
   token = "<your-jwt-token>"
   ```
3. **Open** `LiveKit_ARKit_MinimalSetupApp.swift`.  
4. **Choose one of the two lifecycle configurations**:

---

### A. Global shared instance (original example behavior)

```swift
RoomContextView(lifecycleMode: .globalSharedInstance)
```

→ Produces one reproducible leak after leaving the room.

---

### B. New Room per join (`perConnectionNewInstance`)

```swift
RoomContextView(lifecycleMode: .perConnectionNewInstance)
```

→ Produces more than 24 leaks after rejoining a session.

In this mode:

- `connect()` creates a fresh `Room()`.  
- After `disconnect()`, the previous Room is replaced by a **new placeholder Room**  
  (alternatively it could be set to `nil`, but that's not required for the repro).

5. **Run** the application
6. **Join** a session
7. Activate the camera (top right corner)
8. **Leave** the session
9. Repeat joining a session

However, the **previous** Room instance is no longer referenced anywhere in the app.  
Despite that, Instruments shows multiple LiveKit internal structures as leaked  
(DataChannel / Async / Delegate / StateSync objects, etc.).

### PR DESCRIPTION
**Pull request by pblazej**
Resolves #866

Fixes remaining concurrency antipatterns (mostly implicit `self` inside a long-running `Task`) so that `deinit` (and cancel etc.) is never called.

Introduces `AnyTaskCancellable` wrapper for more Combine-like semantics (RAII).

⚠️ This is a global change affecting core functionality e.g. WebSocket, DataChannel, etc.

### CODE REVIEW

File: Sources/LiveKit/Core/SignalClient.swift [hunk 1]
```diff
@@ -207,14 +202,16 @@ actor SignalClient: Loggable {
     }
 
     func cleanUp(withError disconnectError: Error? = nil) async {
+        if disconnectError is CancellationError { return }
```
Comment (pblazej) [inline Sources/LiveKit/Core/SignalClient.swift]: This is a little ugly and started to fail as the upstream task got (properly?) cancelled, similarly to `Room`:

```swift
if !Task.isCancelled {
  // Finally disconnect if all attempts fail
  await cleanUp(withError: error)
}
```

I don't have any immediate idea here though.

File: Sources/LiveKit/Support/Async/AsyncSequence+Subscribe.swift [hunk 2]
```diff
@@ -0,0 +1,193 @@
...
+    ///
+    /// - Parameters:
+    ///   - observer: The observer object (captured weakly).
+    ///   - priority: The priority of the task.
+    ///   - state: The initial mutable state.
+    ///   - onElement: Called for each element.
+    ///   - onFailure: Called when the sequence terminates with an error. Cancellation errors are ignored.
+    /// - Returns: The task cancellable.
+    func subscribe<O: AnyObject & Sendable, State: Sendable>(
+        _ observer: O,
```
Comment (pblazej) [inline Sources/LiveKit/Support/Async/AsyncSequence+Subscribe.swift:33]: Maybe I'll add some more descriptive label like `subscribe(weakly: self)` etc.

File: Sources/LiveKit/Core/SignalClient.swift (hunk 1 above)
Comment (hiroshihorie) [reply Sources/LiveKit/Core/SignalClient.swift]: How about something like this instead https://github.com/livekit/client-sdk-swift/commit/60536ba4c8ad5c2ffc345ab54034bca3fceda12e

Comment (pblazej) [reply Sources/LiveKit/Core/SignalClient.swift]: Yeah, it boils down to our previous discussion about `type == .cancelled` vs `CancellationError`, I think there should be one single way to propagate that.

At this point I'm fine with both versions, neither is perfect, I'd rather invest into porting that to Rust + proper state machine.

In the future we need a stronger abstraction, something like:

```swift
Task {
   // do something
} cleanup: {
  // defer
}
```

Comment (pblazej) [reply Sources/LiveKit/Core/SignalClient.swift]: Or more event-driven approach...

File: Tests/LiveKitCoreTests/Room/RoomTests.swift [hunk 3]
```diff
@@ -47,8 +47,34 @@ class RoomTests: LKTestCase, @unchecked Sendable {
...
             let socket = await room.signalClient._state.socket
-            self.noLeaks(of: socket!)
+            try self.noLeaks(of: XCTUnwrap(socket))
+
+            let (publisher, subscriber) = room._state.read { ($0.publisher, $0.subscriber) }
+            if let publisher { self.noLeaks(of: publisher) }
+            if let subscriber { self.noLeaks(of: subscriber) }
+
+            self.noLeaks(of: room.publisherDataChannel)
+            self.noLeaks(of: room.subscriberDataChannel)
```
Comment (pblazej) [inline Tests/LiveKitCoreTests/Room/RoomTests.swift:59]: @hiroshihorie I compared with main again and confirmed that the main leak comes from DC (its main event loop).

File: Sources/LiveKit/Core/SignalClient.swift (hunk 1 above)
Comment (pblazej) [reply Sources/LiveKit/Core/SignalClient.swift]: Tested that and it won't work in practice:

```
/Users/blaze/livekit/client-sdk-swift/Tests/LiveKitCoreTests/DataChannel/RealiableDataChannelTests.swift:67 testReliableRetry(): Asynchronous wait failed: Exceeded timeout of 10 seconds, with unfulfilled expectations: "Data received".
```

**Comment by pblazej** [comment]
Linking this one for reference: https://medium.com/the-swift-cooperative/using-async-for-await-youre-probably-doing-it-wrong-88b66fbb0e84

**Comment by pblazej** [comment]
FYI, I added a brand-new SwiftLint rule to prevent bare `Task<>`
