### PR TITLE
Fix broadcast crash in PiP

### LINKED ISSUE #927: Crash in BroadcastImageCodec.jpegDecode when app is backgrounded with PiP screenshare active (iOS) [EXC_BAD_ACCESS (KERN_INVALID_ADDRESS)]
Our iOS app crashes inside the new broadcast IPC pipeline while a LiveKit screen share is being displayed in Picture‑in‑Picture and the main app is in the background.

From the Xcode debugger, the crash happens on a background thread in `BroadcastImageCodec.jpegDecode(_:) ` Please see attached screenshot from Xcode showing the crash and the highlighted code in BroadcastImageCodec.swift.

This occurs while receiving screen‑share video from a remote participant; the user has put the app into the background and is watching the screen share via iOS PiP.

It looks like a decoder crash while converting the incoming JPEG frames to a CVImageBuffer in BroadcastImageCodec.swift.

Steps to reproduce:
- Join a LiveKit room from iOS using the Swift client SDK.
- Have another participant start screen share.
- On the iOS device, enter Picture‑in‑Picture so the screen share continues in a PiP window.
- Background the app (e.g. press Home / swipe up to go to SpringBoard, or switch to another app) while PiP is still showing the remote screen share.
- Keep the call running for a while.
- Result: after some time (often while still in PiP with the app backgrounded), the app crashes with a stack trace showing BroadcastImageCodec.jpegDecode_L_3.

Expected behavior
- The app should not crash while decoding broadcast screen‑share frames.
- Screen share should continue rendering in PiP with the app in the background, or if backgrounding is no longer supported, it should fail gracefully without a decoder crash.

Additional context
- At the time of the crash, the main app is backgrounded and only the PiP window is visible.
- Regular video (camera) and screen share work fine while the app is in the foreground; we have only seen this crash with: App in background & PiP active when Remote screen share ongoing
- I did not find any existing open issue mentioning `BroadcastImageCodec / jpegDecode `crashes. The closest related work I saw was PR #565 “Revamp broadcast IPC”, which introduced `BroadcastImageCodec`.

LiveKit Swift SDK version: 137.7151.10
iOS version: 18.5 
Device: TODO: iPhone 13 Pro Max
Xcode version: 16.2 (16C5032a)

Image

Image

### PR DESCRIPTION
**Pull request by pblazej**
Resolves #927

More (performance) changes may come in #914 
Bg blur uses gpu by default

### CODE REVIEW

**Comment by pblazej** [comment]
I'll rebase the other PR onto that before the release as it contains the drop frame calc.

File: Sources/LiveKit/VideoProcessors/BackgroundBlurVideoProcessor.swift
Comment (hiroshihorie) [inline Sources/LiveKit/VideoProcessors/BackgroundBlurVideoProcessor.swift]: nit: Is this path still invoked for gpu(metal) = false ?

File: Sources/LiveKit/VideoProcessors/BackgroundBlurVideoProcessor.swift [hunk 1]
```diff
@@ -72,8 +72,12 @@ public final class BackgroundBlurVideoProcessor: NSObject, @unchecked Sendable,
     // MARK: Init
 
     /// Initialize the background blur video processor.
-    /// - Parameter highQuality: If true, use more detailed segmentation, but at the cost of performance.
-    public init(highQuality: Bool = true) {
+    /// - Parameters:
+    ///   - highQuality: If true, use more detailed segmentation, but at the cost of performance.
+    ///   - gpu: If true, use GPU rendering for better performance. Set to false when the app may be backgrounded (e.g. during PiP).
+    public init(highQuality: Bool = true, gpu: Bool = true) {
```
Comment (hiroshihorie) [inline Sources/LiveKit/VideoProcessors/BackgroundBlurVideoProcessor.swift]: nit: Maybe `useMetal` better ?

File: Sources/LiveKit/Extensions/CoreImage.swift
Comment (hiroshihorie) [inline Sources/LiveKit/Extensions/CoreImage.swift]: This could be internal / private ?

**Review by hiroshihorie — APPROVED** [review]
✅ LGTM just some nits 🙂

File: Sources/LiveKit/VideoProcessors/BackgroundBlurVideoProcessor.swift
Comment (pblazej) [reply Sources/LiveKit/VideoProcessors/BackgroundBlurVideoProcessor.swift]: Metal attrs should not be harmful, but may introduce copies, so removed them.
