### PR TITLE
Fix preffered buffer size

### LINKED ISSUE #934: kAudioUnitErr_TooManyFramesToProcess (-10874)
**Describe the bug**
When I started a meeting and turned on the microphone, there was a continuous warning log output from the console. The error seemed to be that the frame buffer size configuration of the core audio unit did not match. The error message indicates that the system requires processing 1440 frames, but the current maximum processing capacity of the audio unit configuration is only 1156 frames.

**SDK Version**
2.12.1

**iOS/macOS Version**
iOS

**Xcode Version**
16.2

**Additional Information**
iPhone 14 (iOS 17.4.1)

**Steps to Reproduce**
1. Start a meeting
2. Turn on the microphone

**Logs**
kAudioUnitErr_TooManyFramesToProcess : inFramesToProcess=1440, mMaxFramesPerSlice=1156
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
kAudioUnitErr_TooManyFramesToProcess : inFramesToProcess=1440, mMaxFramesPerSlice=1156
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874
  from AU (0x15921ac70): aumx/mcmx/appl, render err: -10874
  from AU (0x15920f540): augn/sspl/appl, render err: -10874

### PR DESCRIPTION
**Pull request by pblazej**
Resolves #934

### CODE REVIEW

File: Sources/LiveKit/Audio/MixerEngineObserver.swift [hunk 1]
```diff
@@ -96,6 +96,33 @@ public final class MixerEngineObserver: AudioEngineObserver, Loggable {
...
+        //
+        // Complementary to the preferredIOBufferDuration hint set in AudioSessionEngineObserver,
+        // which iOS may ignore on some devices.
+        //
+        // Note: AVAudioEngine may override these values during prepare()/start(), propagating the
+        // outputNode's maximumFramesToRender to all hosted nodes. If that occurs, the actual fix
+        // must move into the WebRTC layer (audio_engine_device.mm).
+        // See: https://developer.apple.com/documentation/audiotoolbox/auaudiounit/maximumframestorender
+        // See: https://developer.apple.com/forums/thread/111968
+        let maxFrames = engine.outputNode.auAudioUnit.maximumFramesToRender
```
Comment (pblazej) [inline Sources/LiveKit/Audio/MixerEngineObserver.swift:111]: I'm getting `outputNode=4096` here, guess it's better than the previous "heuristic" of "2x webrtc size" that may be ignored anyway.

Comment (pblazej) [reply Sources/LiveKit/Audio/MixerEngineObserver.swift:111]: This was the working version before: e75df942e66ca7499753eeb743a75f351a078fa9

Comment (pblazej) [reply Sources/LiveKit/Audio/MixerEngineObserver.swift:111]: We can take `max()` of both, but that's more like guessing.
